#!/usr/bin/env python

import logging
import mycloud
import os
import sys

'''Execute a list of command lines (specified via stdin) in parallel using mycloud.'''

logging.basicConfig(format='%(asctime)s %(filename)s:%(funcName)s %(message)s',
                    level=logging.INFO)

def run_cmd(cmdline):
  os.system(cmdline)
  
if __name__ == '__main__':
  cmds = sys.stdin.read().strip().split('\n')
  cluster = mycloud.Cluster()
  cluster.map(run_cmd, cmds)

